services:
  mongo:
    image: "mongo:latest"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "27017:27017"
networks:
  memphis:
    ipam:
      driver: default
